### ISSUE TITLE
Image tracking

### ISSUE THREAD

**Issue by dmbfm** [jeeliz/jeelizAR#3]
Hi! Thanks for this awesome project!

Can this be used to track an image and estimate it's pose in 3D space, so we can use it as a target in 8thwall?

**Comment by xavierjs** [comment]
Hi,

It can be, but we have to train a specific neural network to do so.
For a custom training you can contact use to contact__at__jeeliz.com
Also, for image detection there are other kinds of algorithms, based on features detection, which can lead to good results.

Best,
Xavier

**Comment by Marcus5234** [comment]
Wait, so  the library can't do image tracking by itself? I need to contact you guys to train the image? How is that useful?? Can't you add a function to make a tracking based on an image? Something [like this](https://www.youtube.com/watch?v=lSkv98epsk8&t=1s)
