### ISSUE TITLE
Possible to use custom NN models as .json? 

### ISSUE THREAD

**Issue by stickyburn** [jeeliz/jeelizAR#4]
Hi there and thank you for this super awesome project!
I wanted to ask if we can use our own neural models and export them as .json to use with the library? I saw that you guys provide personal models for a price, but as a student im financially tied at the moment. 

Thanks again!

**Comment by xavierjs** [comment]
Hi,

Unfortunately it is not possible. Some reasons are explained here: https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2

We are a startup and we are also financially tied at the moment :).

Best,
Xavier
