### ISSUE TITLE
how to track palm lines

### ISSUE THREAD

**Issue by iamappmaker** [jeeliz/jeelizAR#6]
I am trying to create palmistry app. i want to track the palm lines.
Please help me

**Comment by xavierjs** [comment]
Hi,

We can currently work on it, @Jeeliz we provide custom development services.
There is quite a lot of work for this use case. We have to get a dataset or develop a 3D generator, then train a new neuron network model during days and weeks...

You can contact us at contact__at__jeeliz.com to have more information about our rates.

Best,
Xavier
