### ISSUE TITLE
IOS?

### ISSUE THREAD

**Issue by fabiotgolo** [jeeliz/jeelizAR#9]
I tried it on my iPhone 8 IOS 14 in Safari and Google Chrome and didn't work.
It is only for Android?

**Comment by xavierjs** [comment]
On IOS it works only with Safari for IOS < 14.3
It should work with Chrome & IOS >= 14.3

**Comment by fabiotgolo** [comment]
Hi Xavier!
My tests were in these browsers and didn't work.

**Comment by xavierjs** [comment]
Hi @fabiotgolo 

Does MediaStream API work?
i.e. can you get the camera video stream in these browsers?
Can you test here: https://webrtc.github.io/samples/src/content/getusermedia/gum/

What is your IOS full version? Is it 14.3?

**Comment by xavierjs** [comment]
Hi  @fabiotgolo 

Oh I did not see it was an issue about JeelizAR, I thought it was about Jeeliz FaceFilter.
This library is not maintained anymore so it is normal it does not work with these browsers.

Best,
Xavier
